# _config.yml 配置示例
title: "我的 GitHub 教程博客"
description: "这是一个分享 GitHub 和编程教程的博客，专注于 Markdown 格式的教程。"
theme: jekyll-theme-cayman  # 你可以根据需求选择其他主题
url: "https://fan-lin.github.io"  # 你的 GitHub Pages 地址
baseurl: ""  # 不需要设置，保持空白

# 导航设置
social_links:
  twitter: "https://twitter.com/fan-lin"
  github: "https://github.com/fan-lin"
