title: Fan-Lin
description: 个人教程与学习笔记
url: "https://fan-lin.github.io"
baseurl: ""

remote_theme: just-the-docs/just-the-docs

color_scheme: default
search_enabled: true
heading_anchors: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
